packages:
  - "cli"
  - "sdk/typescript"
  - "packages/*"
  - "test/e2e"

allowBuilds:
  "@playwright/browser-chromium": true
  esbuild: true

minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - "@lrail/*"
