apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - name: lrail-trivy-db-updater
    namespace: lrail-build-control
    files:
      - update.sh=scripts/update-trivy-db.sh
generatorOptions:
  disableNameSuffixHash: true
resources:
  - namespaces.yaml
  - runtime.yaml
  - rbac.yaml
  - storage-and-quota.yaml
  - certificates.yaml
  - egress-proxy.yaml
  - registry-broker.yaml
  - evidence-signer.yaml
  - trivy-db-updater.yaml
  - controller.yaml
  - residue-agent.yaml
  - network-policy.yaml
  - admission-policy.yaml
