apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lrail-build-broker-state
  namespace: lrail-control
spec:
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lrail-build-state
  namespace: lrail-build-control
spec:
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lrail-build-registry-state
  namespace: lrail-build-control
spec:
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lrail-build-trivy-db
  namespace: lrail-build-control
spec:
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lrail-build-cache
  namespace: lrail-build-control
spec:
  storageClassName: standard
