AllCops:
  NewCops: enable
  TargetRubyVersion: 3.4
  SuggestExtensions: false
  Exclude:
    - "vendor/**/*"

Layout/SpaceInsideArrayLiteralBrackets:
  EnforcedStyle: space

Layout/LineLength:
  Max: 120

Metrics/AbcSize:
  Max: 30

Metrics/MethodLength:
  Max: 30

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: no_comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: no_comma
