source "https://rubygems.org"

ruby "3.4.10"

gem "temporalio", "1.5.0"

group :development, :test do
  gem "bundler-audit", "~> 0.9", require: false
  gem "minitest", "~> 5.27"
  gem "rake", "~> 13.3"
  gem "rubocop", "~> 1.88", require: false
end
