package buildorchestrator

import (
	"bytes"
	"errors"
	"fmt"
	"path"
	"regexp"
	"slices"
	"strconv"
	"strings"

	"github.com/mayowaoladosu/layerrail-lrail/services/build-plane/internal/llbcompiler"
)

const GeneratedRecipeVersion = "1.0.0"

var variableNamePattern = regexp.MustCompile(`[^a-z0-9_]`)

type BaseCatalog struct {
	Version string      `json:"version"`
	Entries []BaseEntry `json:"entries"`
}

type BaseEntry struct {
	Language string                   `json:"language"`
	Material llbcompiler.BaseMaterial `json:"material"`
}

func (catalog BaseCatalog) Validate(policy llbcompiler.Policy) error {
	if !semanticVersionPattern.MatchString(catalog.Version) || len(catalog.Entries) == 0 || len(catalog.Entries) > 32 {
		return errors.New("base catalog identity or size is invalid")
	}
	languages := make([]string, 0, len(catalog.Entries))
	for _, entry := range catalog.Entries {
		if !slices.Contains([]string{"ruby", "node", "python", "go", "docker"}, entry.Language) || entry.Material.RequestedRef == "" ||
			entry.Material.RequestedRef != entry.Material.ResolvedRef || !strings.HasSuffix(entry.Material.RequestedRef, "@"+entry.Material.Digest) ||
			!slices.Contains(policy.Base.AllowedRegistries, entry.Material.Registry) || !slices.Contains(policy.Base.AllowedSignatureIdentities, entry.Material.SignatureIdentity) {
			return errors.New("base catalog entry is invalid")
		}
		expected, err := llbcompiler.ResolutionDigest(entry.Material)
		if err != nil || expected != entry.Material.ResolutionDigest {
			return errors.New("base catalog resolution evidence is invalid")
		}
		languages = append(languages, entry.Language)
	}
	if !slices.IsSorted(languages) || len(slices.Compact(append([]string(nil), languages...))) != len(languages) {
		return errors.New("base catalog languages must be sorted and unique")
	}
	return nil
}

func (catalog BaseCatalog) material(language, platform string) (llbcompiler.BaseMaterial, error) {
	for _, entry := range catalog.Entries {
		if entry.Language == language && slices.Contains(entry.Material.Platforms, platform) {
			return entry.Material, nil
		}
	}
	return llbcompiler.BaseMaterial{}, fmt.Errorf("no approved %s base supports %s", language, platform)
}

func GenerateRecipe(result DetectionResult, catalog BaseCatalog, platform string) ([]byte, []llbcompiler.BaseMaterial, error) {
	if result.Blocked || len(result.Services) == 0 || result.GeneratedManifest == nil || string(result.GeneratedManifest) == "null" {
		return nil, nil, errors.New("detector proposal requires confirmation")
	}
	var program bytes.Buffer
	fmt.Fprintf(&program, "# Generated by Lrail detector recipe translator %s\n", GeneratedRecipeVersion)
	materials := make([]llbcompiler.BaseMaterial, 0, len(result.Services))
	seenMaterials := make(map[string]struct{})
	for index, service := range result.Services {
		if service.Ambiguous || len(service.UnsupportedFeatures) != 0 || service.Build.Strategy != "auto" {
			return nil, nil, fmt.Errorf("automatic recipe for %s is unresolved or unsupported", service.Name)
		}
		if service.Kind == "static" || service.Language == "static" || service.Language == "docker" {
			return nil, nil, fmt.Errorf("automatic %s recipe requires an explicit repository build definition", service.Language)
		}
		material, err := catalog.material(service.Language, platform)
		if err != nil {
			return nil, nil, err
		}
		if _, exists := seenMaterials[material.RequestedRef]; !exists {
			materials = append(materials, material)
			seenMaterials[material.RequestedRef] = struct{}{}
		}
		prefix := fmt.Sprintf("s%d_%s", index+1, variableName(service.Name))
		workdir := "/workspace"
		if service.Root != "." {
			workdir += "/" + service.Root
		}
		fmt.Fprintf(&program, "%s_src = source(path = %s, include = [\"**\"], exclude = [\".git/**\"])\n", prefix, quote("."))
		fmt.Fprintf(&program, "%s_base = image(ref = %s)\n", prefix, quote(material.RequestedRef))
		stateIndex := 1
		currentState := fmt.Sprintf("%s_state_%d", prefix, stateIndex)
		fmt.Fprintf(&program, "%s = copy(base = %s_base, src = %s_src, dest = \"/workspace\", owner = \"10001:10001\", mode = \"0755\")\n", currentState, prefix, prefix)
		mountNames := make([]string, 0, len(service.Build.CachePaths))
		for cacheIndex, cachePath := range service.Build.CachePaths {
			absolute := "/workspace/" + strings.TrimPrefix(cachePath, "./")
			cacheName := fmt.Sprintf("%s-cache-%d", service.Name, cacheIndex+1)
			variable := fmt.Sprintf("%s_cache_%d", prefix, cacheIndex+1)
			fmt.Fprintf(&program, "%s = cache(name = %s, target = %s, sharing = \"locked\")\n", variable, quote(cacheName), quote(absolute))
			mountNames = append(mountNames, variable)
		}
		environment := recipeEnvironment(service.Language, workdir)
		if len(service.Build.InstallCommand) != 0 {
			stateIndex++
			nextState := fmt.Sprintf("%s_state_%d", prefix, stateIndex)
			fmt.Fprintf(&program, "%s = run(base = %s, argv = %s, env = %s, mounts = %s, network = \"packages\", user = \"10001:10001\", workdir = %s)\n",
				nextState, currentState, stringList(service.Build.InstallCommand), stringMap(environment), expressionList(mountNames), quote(workdir))
			currentState = nextState
		}
		if len(service.Build.BuildCommand) != 0 {
			stateIndex++
			nextState := fmt.Sprintf("%s_state_%d", prefix, stateIndex)
			fmt.Fprintf(&program, "%s = run(base = %s, argv = %s, env = %s, mounts = %s, network = \"packages\", user = \"10001:10001\", workdir = %s)\n",
				nextState, currentState, stringList(service.Build.BuildCommand), stringMap(environment), expressionList(mountNames), quote(workdir))
			currentState = nextState
		}
		command, ports, err := runtimeCommand(service, workdir)
		if err != nil {
			return nil, nil, err
		}
		labels := map[string]string{
			"dev.lrail.framework": strings.ToLower(strings.ReplaceAll(service.Framework, " ", "-")),
			"dev.lrail.language":  service.Language,
			"dev.lrail.recipe":    GeneratedRecipeVersion,
		}
		fmt.Fprintf(&program, "artifact(name = %s, state = %s, entrypoint = [], cmd = %s, ports = %s, labels = %s)\n\n",
			quote(service.Name), currentState, stringList(command), intList(ports), stringMap(labels))
	}
	slices.SortFunc(materials, func(left, right llbcompiler.BaseMaterial) int {
		return strings.Compare(left.RequestedRef, right.RequestedRef)
	})
	return program.Bytes(), materials, nil
}

func runtimeCommand(service DetectedService, workdir string) ([]string, []int, error) {
	selected := -1
	for index, process := range service.Processes {
		if process.Kind == "web" || process.Kind == "private_service" {
			selected = index
			break
		}
		if selected == -1 && process.Kind != "release" && process.Kind != "static" {
			selected = index
		}
	}
	if selected == -1 || len(service.Processes[selected].Command) == 0 {
		return nil, nil, errors.New("detector proposal has no runtime process")
	}
	command := append([]string(nil), service.Processes[selected].Command...)
	if strings.HasPrefix(command[0], "/app/") {
		command[0] = workdir + strings.TrimPrefix(command[0], "/app")
	}
	ports := make([]int, 0, len(service.Processes))
	for _, process := range service.Processes {
		if process.Port != nil {
			ports = append(ports, *process.Port)
		}
	}
	slices.Sort(ports)
	ports = slices.Compact(ports)
	return command, ports, nil
}

func recipeEnvironment(language, workdir string) map[string]string {
	environment := map[string]string{"HOME": workdir + "/.home"}
	switch language {
	case "go":
		environment["GOCACHE"] = workdir + "/.cache/go-build"
		environment["GOMODCACHE"] = workdir + "/.cache/go-mod"
		environment["CGO_ENABLED"] = "0"
	case "node":
		environment["NODE_ENV"] = "production"
		environment["npm_config_cache"] = workdir + "/.cache/npm"
	case "python":
		environment["UV_CACHE_DIR"] = workdir + "/.cache/uv"
		environment["UV_PROJECT_ENVIRONMENT"] = workdir + "/.venv"
	case "ruby":
		environment["BUNDLE_PATH"] = workdir + "/vendor/bundle"
		environment["BUNDLE_FROZEN"] = "true"
		environment["RAILS_ENV"] = "production"
	}
	return environment
}

func variableName(value string) string {
	return strings.Trim(variableNamePattern.ReplaceAllString(strings.ToLower(value), "_"), "_")
}

func quote(value string) string { return strconv.Quote(value) }

func stringList(values []string) string {
	quoted := make([]string, len(values))
	for index, value := range values {
		quoted[index] = quote(value)
	}
	return "[" + strings.Join(quoted, ", ") + "]"
}

func expressionList(values []string) string { return "[" + strings.Join(values, ", ") + "]" }

func intList(values []int) string {
	result := make([]string, len(values))
	for index, value := range values {
		result[index] = strconv.Itoa(value)
	}
	return "[" + strings.Join(result, ", ") + "]"
}

func stringMap(values map[string]string) string {
	keys := make([]string, 0, len(values))
	for key := range values {
		keys = append(keys, key)
	}
	slices.Sort(keys)
	pairs := make([]string, 0, len(keys))
	for _, key := range keys {
		pairs = append(pairs, quote(key)+": "+quote(values[key]))
	}
	return "{" + strings.Join(pairs, ", ") + "}"
}

func selectedBuildFile(root, buildFile string) string {
	if root == "." {
		return buildFile
	}
	return path.Join(root, buildFile)
}
