# syntax=docker/dockerfile:1.12
FROM golang:1.26.5-alpine@sha256:0178a641fbb4858c5f1b48e34bdaabe0350a330a1b1149aabd498d0699ff5fb2 AS trivy-build
ENV GOEXPERIMENT=jsonv2
WORKDIR /src
ADD --checksum=sha256:5a922c388846d11345ce8283e4373be312458f002abc667c3cd1f77c43163725 \
    https://github.com/aquasecurity/trivy/archive/8a32853686209a428179bb3a1688802b25691564.tar.gz /tmp/trivy.tar.gz
RUN --mount=type=cache,id=lrail-trivy-go-mod,target=/go/pkg/mod \
    tar -xzf /tmp/trivy.tar.gz --strip-components=1 \
 && go mod edit -require=oras.land/oras-go/v2@v2.6.2 \
 && go mod tidy \
 && go mod download
RUN --mount=type=cache,id=lrail-trivy-go-mod,target=/go/pkg/mod \
    --mount=type=cache,id=lrail-trivy-go-build,target=/root/.cache/go-build \
    CGO_ENABLED=0 GOOS=linux go build -trimpath -buildvcs=false \
      -ldflags='-s -w -X=github.com/aquasecurity/trivy/pkg/version/app.ver=0.72.0' \
      -o /out/trivy ./cmd/trivy

FROM gcr.io/distroless/static-debian12:nonroot@sha256:b7bb25d9f7c31d2bdd1982feb4dafcaf137703c7075dbe2febb41c24212b946f AS certs
FROM alpine:3.24.1@sha256:28bd5fe8b56d1bd048e5babf5b10710ebe0bae67db86916198a6eec434943f8b
COPY --from=certs /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
COPY --from=trivy-build /out/trivy /usr/local/bin/trivy
LABEL org.opencontainers.image.source="https://github.com/mayowaoladosu/layerrail-lrail" \
      org.opencontainers.image.licenses="LicenseRef-Proprietary" \
      org.opencontainers.image.title="Lrail Trivy database updater" \
      dev.lrail.upstream.trivy.commit="8a32853686209a428179bb3a1688802b25691564" \
      dev.lrail.upstream.oras.version="v2.6.2"
ENTRYPOINT ["/usr/local/bin/trivy"]
