apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - site-config.yaml
  - site-private-network-policy.yaml
patches:
  - path: site-network-policy-patch.yaml
  - path: site-private-endpoints-patch.yaml
  - path: site-storage-patch.yaml
